name: qa-dev

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: qa-tests
    container:
      image: maven:3.8.4-jdk-8
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean verify -Dparallel.tests.count=10